name: docker build test

on:
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          tags: theapp:latest
          build-args: |
            "NEXT_PUBLIC_BEE_URL=http://localhost:1635"
            "NEXT_PUBLIC_BEE_DEBUG_URL=http://localhost:1635"
            "NEXT_PUBLIC_GLOBAL_BATCH_ID=b48953f094938e65f64addef4049b1f41b8140f3673053f2bb0db74b0b15f7be"
            "NEXT_PUBLIC_FAIROSHOST=http://localhost"
            "NEXT_PUBLIC_FAIRDRIVEHOST=http://localhost"
            "NEXT_PUBLIC_BLOCKCHAIN_INFO=blockchanin"
            "NEXT_PUBLIC_ENVIRONMENT=TEST"
            "NEXT_PUBLIC_CREATE_ACCOUNT_REDIRECT=http://localhost"
            "NEXT_PUBLIC_BB_RULES_URL=https://create.dev.fairdatasociety.org/#/bb-rules"
            "NEXT_PUBLIC_BB_API_URL=https://bbapi.fairdatasociety.org"
