name: docker build test

on:
  pull_request:
    branches:
      - '**'

env:
  BEE_VERSION: '1.6.1'
  REACT_APP_BEE_URL: http://localhost:1633
  NEXT_PUBLIC_BEE_URL: http://localhost:1633
  REACT_APP_BEE_DEBUG_URL: http://localhost:1635
  NEXT_PUBLIC_BEE_DEBUG_URL: http://localhost:1635
  NEXT_PUBLIC_RPC_URL: https://xdai.dev.fairdatasociety.org
  NEXT_PUBLIC_ENS_REGISTRY_ADDRESS: '0x42B22483e3c8dF794f351939620572d1a3193c12'
  NEXT_PUBLIC_SUBDOMAIN_REGISTRAR_ADDRESS: '0xF4C9Cd25031E3BB8c5618299bf35b349c1aAb6A9'
  NEXT_PUBLIC_PUBLIC_RESOLVER_ADDRESS: '0xbfeCC6c32B224F7D0026ac86506Fe40A9607BD14'
  NEXT_PUBLIC_GLOBAL_BATCH_ID: 'b48953f094938e65f64addef4049b1f41b8140f3673053f2bb0db74b0b15f7be'
  NEXT_PUBLIC_FAIROSHOST: http://localhost
  NEXT_PUBLIC_FAIRDRIVEHOST: http://localhost
  NEXT_PUBLIC_BLOCKCHAIN_INFO: blockchanin
  NEXT_PUBLIC_ENVIRONMENT: environment
  NEXT_PUBLIC_GLOBAL_BATCH_ID: batchid
  NEXT_PUBLIC_CREATE_ACCOUNT_REDIRECT: http://localhost

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: build
      run: docker build .
