name: Node.js CI

on:
  push:
    branches:
      - master
      - development

env:
  BEE_VERSION: '1.6.3'
  REACT_APP_BEE_URL: http://localhost:1633
  REACT_APP_BEE_DEBUG_URL: http://localhost:1635
# NEXT_PUBLIC_RPC_URL=https://goerli.infura.io/v3/92ed13edfad140409ac24457a9c4e22d
# NEXT_PUBLIC_ENS_REGISTRY_ADDRESS=0x42B22483e3c8dF794f351939620572d1a3193c12
# NEXT_PUBLIC_SUBDOMAIN_REGISTRAR_ADDRESS=0xF4C9Cd25031E3BB8c5618299bf35b349c1aAb6A9
# NEXT_PUBLIC_PUBLIC_RESOLVER_ADDRESS=0xbfeCC6c32B224F7D0026ac86506Fe40A9607BD14

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Install fdp-play
      run: npm install -g @fairdatasociety/fdp-play

    - name: Run fdp-play
      run: fdp-play start -d --bee-version $BEE_VERSION    
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
    - name: build
      run: yarn build
      env:
        CI: false
